server:
  port: 8282
spring:
  application:
    name: cms-backend-api-service-reactive
  profiles:
    active: local

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true



graphql:
  extended-scalars: Date
---
spring:
  config:
    activate:
      on-profile: "local"
  data:
    mongodb:
      uri: mongodb://localhost:27017/turbine-cms
  boot:
    admin:
      client:
        url:
          - http://localhost:8989
management:
  endpoints:
    web:
      exposure:
        include: "*"